#include <bits/stdc++.h>
using namespace std;


int main()
{

  // ZADANIA 1D:
  //1. wyswietl liczby od 1 do 10
  //2. wyswietl liczby od 100 do 150
  //3. wyswietl liczby od 1 do 10 - tylko parzyste
  // - modulo
  // - bez if

  //ZADANIA 2D:
  //4. wyswietl kwadrat z kropek 5x5
  // .....
  // .....
  // .....
  // .....
  // .....
  // - jedna petla for 
  // - dwie petle for
  //5. wyswietl trapez z kropek 5x5
  // .....
  //  .....
  //   .....
  //    .....
  //     .....
  // - jedna petla for
  // - dwie petle for
  //6. wyswietl trójkąt z kropek 5x5
  //.
  //..
  //...
  //....
  //.....

  //   .
  //  ...
  // .....
  //.......
  // .....
  //  ...
  //   .
}